language: generic

matrix:
  include:
    - os: linux
      sudo: required
      dist: bionic
      before_install:
        - sudo -E add-apt-repository -y ppa:chris-lea/libsodium
        - sudo apt-get update && sudo apt-get install -y libsodium-dev
      install:
        - eval "$(curl -sL https://swiftenv.fuller.li/en/latest/install.sh)"

    - os: osx
      osx_image: xcode12.2
      before_install:
        - brew update
        - brew install libsodium

script:
  - swift build
